# Pre-requisite: playbook setup-prod.yml

- hosts: prod

  vars:
    installDependencies: true
    createNetworks: true

    renewCertificates: true

    # # certificate details
    wildcardDomain: wires.fr
    notificationEmail: antoine.gautrain@gmail.com
    renewalThreshold: 30

  roles:
    - role: dependencies
      when: installDependencies | default(false)

    - role: firewall
      when: installDependencies | default(false)

    - role: docker
      when: installDependencies | default(false)

    - role: certificates
      when: renewCertificates | default(false)

    - role: infra-prod
