# SSH Configuration for Wires Infrastructure
# Generated by Terraform

# Bastion host for production environment
Host wires-prod-bastion
    HostName ${bastion_ip}
    User bastion
    Port ${bastion_port}
    IdentityFile ~/.ssh/id_rsa

# Production servers
%{ for instance in prod_servers ~}
Host ${instance.name}
    HostName ${[for ip in instance.private_ips : ip.address if can(regex("^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$", ip.address))][0]}
    User root
    IdentityFile ~/.ssh/id_rsa
%{ if instance.public_ip == null || instance.public_ip == "" ~}
    ProxyJump wires-prod-bastion
%{ endif ~}

%{ endfor ~}

# Development servers
%{ for instance in dev_servers ~}
Host ${instance.name}
    HostName ${instance.public_ip != null ? instance.public_ip : instance.private_ip}
    User root
    IdentityFile ~/.ssh/id_rsa

%{ endfor ~}
