---

- name: Check if mongosh is available
  ansible.builtin.raw: which mongosh
  check_mode: false
  changed_when: false
  failed_when: which_mongosh.rc > 1
  register: which_mongosh

- name: Debug mongosh availability
  debug:
    msg: "{{ which_mongosh }}"

- name: Fetch mongo shell package
  command: wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.3.3_amd64.deb

- name: Install mongo shell
  become: true
  command: apt install ./mongodb-mongosh_2.3.3_amd64.deb


- name: Alter /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.address }}     {{ item.hostname }}"
    state: present
  loop:
    - hostname: mgo01.wires.fr
      address: 10.1.2.250
    - hostname: mgo02.wires.fr
      address: 10.1.2.250
    - hostname: mgo03.wires.fr
      address: 10.1.2.250

- name: Create database directory
  file:
    path: "{{ basePath }}/database"
    state: directory

- name: Create database secrets directory
  file:
    path: "{{ basePath }}/database/secrets"
    state: directory

- name: Create config directories
  file:
    path: "{{ basePath }}/database/{{ item }}_config"
    state: directory
  loop:
    - mgo01
    - mgo02
    - mgo03

- name: Create data directories
  file:
    path: "{{ basePath }}/database/{{ item }}_data"
    state: directory
  loop:
    - mgo01
    - mgo02
    - mgo03

- name: Place keyfile secret
  copy: src=files/database/secrets/keyfile dest={{ basePath }}/database/secrets/keyfile mode=0400

# Hack to ensure keyfile has mongodb:mongodb permissions
- name: Changing keyfile owner
  become: true
  shell: chown 999:999 {{ basePath }}/database/secrets/keyfile

- name: Ensure bridge network is available for MongoDB
  command: docker network create mongo-network
  ignore_errors: yes
  when: createNetworks | default(false)