- name: Create Portainer directory
  file:
    path: ~/infra-dev/portainer
    state: directory

- name: Create Portainer data directory
  file:
    path: ~/infra-dev/portainer/data
    state: directory